from flask import Flask, render_template, request # import flask
import openai # import openai

app = Flask(__name__)

# Set OpenAI API key 
openai.api_key = ''

def grade_essay(essay_text): # prompt for gpt 3.5
    prompt = f"Please analyze and grade the following essay: {essay_text}\n\nCriteria:\n1. Content and Understanding (40%): Assess the depth of understanding, accuracy of information, and quality of arguments and supporting evidence.\n2. Organization and Structure (20%): Evaluate the overall organization, clarity of the thesis statement, logical flow of ideas, and paragraph transitions.\n3. Coherence and Clarity (20%): Examine sentence structure, clarity of expression, and use of vocabulary.\n4. Grammar and Mechanics (10%): Check for grammatical errors, spelling, punctuation, and adherence to writing conventions.\n5. Citations and References (10%): Assess the use of citations and references, if applicable.\n\nPlease provide a percentage grade and brief feedback on strengths and weaknesses in these areas. Your evaluation should be concise and constructive."

    try:
        response = openai.Completion.create(
            engine="davinci",  # Use Davinci engine
            prompt=prompt,
            max_tokens=1000  # Adjust value how many tokens max
        )

        graded_essay = response.choices[0].text
        return graded_essay # output generated by ai
    except Exception as error: # throw error if something wrong with input or cannot give the output
        return f"An error occurred: {str(error)}"


@app.route('/')
def index():
    return render_template('index.html') # front end html

@app.route('/grade', methods=['POST'])

def grade_essay_request():
    essay_text = request.form['essay_text']

    # Call the grade_essay function to grade it
    grading_result = grade_essay(essay_text)

    # Render 'index.html' and pass the grading result
    return render_template('result.html', result=grading_result)

if __name__ == '__main__':
    app.run(debug=True)
